Repository Leafwing-Studios/leafwing-website, pull requests merged in 2022-06, with the labels that each got.

#94 Make the existing content pages less bad and weird
  .github/linters/.markdown-lint.yml
  content/_index.md
  content/about/index.md
  content/blog/post-0.md
  content/blog/post-1.md
  content/blog/post-2.md
  content/projects/index.md
  themes/lws/sass/_text.scss
Labels: polish

#97 Add information about stack to README
  README.md
Labels: documentation, meta

#99 Format HTML / CSS files
  sass/_dark.scss
  static/addition.css
  static/browserconfig.xml
  static/main.css
  static/main.js
  templates/about.html
  templates/blog-section.html
  templates/mailing-list.html
  templates/projects.html
  themes/lws/sass/_markdown.scss
  themes/lws/sass/common/_dark.scss
  themes/lws/sass/common/_variables.scss
  themes/lws/sass/lws.scss
  themes/lws/static/normalize.css
  themes/lws/templates/categories/list.html
  themes/lws/templates/categories/single.html
  themes/lws/templates/index.html
  themes/lws/templates/page.html
  themes/lws/templates/tags/list.html
  themes/lws/templates/tags/single.html
  themes/lws/theme.toml
  themes/lws/vercel.json
Labels: code-quality

#100 Fix CSS problems introduced by autoformatting
  themes/lws/templates/index.html
Labels: polish

#102 Add test blog post
  content/blog/_index.md
  content/blog/post/test-post.md
Labels: code-quality

#105 Remove 15k lines of auto-generated bootstrap CSS
  static/main.css
Labels: polish, code-quality

#107 Cleanup work for blog templates
  content/blog/test-post-0.md
  content/blog/test-post-1.md
  templates/blog-section.html
  themes/lws/sass/_text.scss
  themes/lws/templates/page.html
Labels: code-quality

#108 Button fixes
  sass/_dark.scss
  static/addition.css
  templates/blog-section.html
  themes/lws/sass/bootstrap/scss/_button-group.scss
  themes/lws/sass/bootstrap/scss/_buttons.scss
  themes/lws/sass/bootstrap/scss/_images.scss
  themes/lws/sass/bootstrap/scss/_mixins.scss
  themes/lws/sass/bootstrap/scss/bootstrap.scss
  themes/lws/sass/bootstrap/scss/mixins/_border-radius.scss
  themes/lws/sass/bootstrap/scss/mixins/_box-shadow.scss
  themes/lws/sass/bootstrap/scss/mixins/_breakpoints.scss
  themes/lws/sass/bootstrap/scss/mixins/_buttons.scss
  themes/lws/sass/bootstrap/scss/mixins/_deprecate.scss
  themes/lws/sass/bootstrap/scss/mixins/_gradients.scss
  themes/lws/sass/bootstrap/scss/mixins/_image.scss
  themes/lws/sass/bootstrap/scss/mixins/_text-truncate.scss
  themes/lws/sass/bootstrap/scss/mixins/_transition.scss
  themes/lws/sass/bootstrap/scss/mixins/_utilities.scss
  themes/lws/sass/bootstrap/scss/vendor/_rfs.scss
  themes/lws/sass/common/_dark.scss
Labels: polish, code-quality

#109 Misc cleanup
  content/projects/index.md
  sass/_dark.scss
  themes/lws/sass/bootstrap/LICENSE
  themes/lws/sass/bootstrap/README.md
  themes/lws/sass/bootstrap/package.json
  themes/lws/sass/bootstrap/scss/_functions.scss
  themes/lws/sass/bootstrap/scss/_variables.scss
  themes/lws/sass/bootstrap/scss/bootstrap.scss
  themes/lws/sass/common/_dark.scss
  themes/lws/sass/common/_variables.scss
  themes/lws/sass/lws.scss
  themes/lws/templates/index.html
Labels: code-quality

#110 Remove theme
  config.toml
  sass/_markdown.scss
  sass/_text.scss
  sass/_utility.scss
  sass/common/_dark.scss
  sass/common/_variables.scss
  sass/lws.scss
  static/normalize.css
  templates/_macros.html
  templates/_variables.html
  templates/about.html
  templates/blog-section.html
  templates/categories/list.html
  templates/categories/single.html
  templates/index.html
  templates/mailing-list.html
  templates/page.html
  templates/projects.html
  templates/tags/list.html
  templates/tags/single.html
  themes/lws/LICENSE
  themes/lws/config.toml
  themes/lws/theme.toml
Labels: code-quality

#111 Add blog page, various style fixes
  content/blog/test-post-0.md
  content/blog/test-post-1.md
  sass/_markdown.scss
  sass/_text.scss
  sass/lws.scss
  templates/_macros.html
  templates/_variables.html
  templates/blog-post.html
  templates/blog-section.html
  templates/index.html
  templates/page.html
Labels: polish, code-quality

#112 Remove some of the awful mysterious css imports
  sass/_text.scss
  sass/lws.scss
  templates/index.html
Labels: code-quality

#113 Assorted cleanup
  config.toml
  content/blog/test-post-0.md
  content/blog/test-post-1.md
  sass/_colors.scss
  sass/_dark-mode.scss
  sass/_markdown.scss
  sass/_text.scss
  sass/_utility.scss
  sass/common/_variables.scss
  sass/lws.scss
  static/browserconfig.xml
  static/dark-mode.js
  static/fonts.css
  static/main.css
  static/normalize.css
  templates/_macros.html
  templates/_variables.html
  templates/blog-section.html
  templates/categories/list.html
  templates/categories/single.html
  templates/index.html
  templates/tags/list.html
  templates/tags/single.html
Labels: code-quality

#114 Improve footer
  templates/index.html
Labels: polish, user experience

#115 Fix footer
  sass/_dark-mode.scss
  sass/lws.scss
  templates/index.html
Labels: polish

#116 Clean up index.html and move away from hero image
  config.toml
  content/_index.md
  content/team/index.md
  sass/lws.scss
  templates/blog-post.html
  templates/blog-section.html
  templates/home.html
  templates/index.html
  templates/mailing-list.html
  templates/page.html
  templates/projects.html
  templates/team.html
Labels: polish, code-quality

#117 De-macroify header creation
  content/blog/_index.md
  templates/_macros.html
  templates/blog-section.html
  templates/index.html
  templates/tags/single.html
Labels: code-quality

#118 Remove bulma css dependency
  sass/_layout.scss
  sass/_pagination.scss
  sass/lws.scss
  templates/_macros.html
  templates/blog-section.html
  templates/index.html
  templates/tags/single.html
Labels: code-quality

#119 Remove dark mode
  sass/_dark-mode.scss
  sass/lws.scss
  static/dark-mode.js
  templates/index.html
Labels: polish, code-quality

#120 Clean up of blog cards
  sass/_layout.scss
  templates/_macros.html
  templates/tags/list.html
  templates/tags/single.html
Labels: polish, code-quality

#122 Font twiddling
  content/blog/test-post-1.md
  content/projects/index.md
  sass/_colors.scss
  sass/_footer.scss
  sass/_header.scss
  sass/_layout.scss
  sass/_markdown.scss
  sass/_table-of-contents.scss
  sass/_text.scss
  sass/_utility.scss
  sass/lws.scss
  templates/projects.html
Labels: polish, code-quality

#123 Make pagination not embarassingly bad
  content/blog/test-post-0 copy 10.md
  content/blog/test-post-0 copy 11.md
  content/blog/test-post-0 copy 12.md
  content/blog/test-post-0 copy 2.md
  content/blog/test-post-0 copy 3.md
  content/blog/test-post-0 copy 4.md
  content/blog/test-post-0 copy 5.md
  content/blog/test-post-0 copy 6.md
  content/blog/test-post-0 copy 7.md
  content/blog/test-post-0 copy 8.md
  content/blog/test-post-0 copy 9.md
  content/blog/test-post-0 copy.md
  sass/_pagination.scss
  templates/blog-section.html
  templates/index.html
  templates/tags/list.html
  templates/tags/single.html
Labels: polish

#131 Color cleanup
  sass/_colors.scss
  sass/_footer.scss
  sass/_header.scss
  sass/_layout.scss
  sass/_table-of-contents.scss
  sass/_text.scss
  templates/blog-section.html
  templates/index.html
Labels: polish, code-quality

#133 Remove dead dark mode code
  templates/index.html
Labels: code-quality

#137 Fix broken Twitch link
  content/team/index.md
Labels: bug, marketing

#144 Improve color contrast
  sass/_colors.scss
  sass/_table-of-contents.scss
Labels: polish, accessibility

#147 Emails should use mailto links
  content/team/index.md
Labels: polish, user experience

#150 Add link to tags
  templates/_macros.html
Labels: polish, user experience

#151 Tweak appearance of pagination
  sass/_pagination.scss
  sass/lws.scss
Labels: polish

#152 Fix typo
  content/projects/index.md
Labels: bug, content

#153 Make the ToC prettier
  sass/_blog-cards.scss
  sass/_table-of-contents.scss
  templates/index.html
Labels: polish

#156 Footer should be pushed to bottom
  sass/lws.scss
Labels: polish

#158 Fix broken link to mailing list
  content/projects/index.md
Labels: bug, marketing

#159 Remove test posts
  content/blog/test-post-0 copy 10.md
  content/blog/test-post-0 copy 11.md
  content/blog/test-post-0 copy 12.md
  content/blog/test-post-0 copy 2.md
  content/blog/test-post-0 copy 3.md
  content/blog/test-post-0 copy 4.md
  content/blog/test-post-0 copy 5.md
  content/blog/test-post-0 copy 6.md
  content/blog/test-post-0 copy 7.md
  content/blog/test-post-0 copy 8.md
  content/blog/test-post-0 copy 9.md
  content/blog/test-post-0 copy.md
  content/blog/test-post-0.md
  content/blog/test-post-1.md
Labels: polish

#161 Add a promotional image to home screen
  sass/_home.scss
  sass/lws.scss
  static/bladesworn-concept.svg
  templates/home.html
Labels: polish, marketing
